version: '3.8'

services:
  bot:
    build: .
    container_name: xui-tg-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./users.json:/app/users.json
      - ./admins.json:/app/admins.json
